version: '3.8'
services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./user_code/frontend:/usr/share/nginx/html:ro
    ports:
      - '8080:80'
    restart: unless-stopped
  nginx-proxy:
    image: nginx:alpine
    ports:
      - '8081:80'
    volumes:
      - ./infra/nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
